#config_version=5

hardware:
  platform: fast
  driverboards: fast

fast:
  ports: com5  # Adjust this to match your COM port
  baud: 921600
  debug: false
  
mpf:
  paths:
    modes: modes
  allow_invalid_config_sections: true
  save_machine_vars_to_disk: true
  
config_players:
  slide_player: "slides.yaml"
  widget_player: "widgets.yaml"
  light_player: "lights.yaml"
  
fast_coil_settings: {}  # Configure based on coil specs
fast_switch_settings: {}  # Configure based on switch specs

switches:
  # Trough Switches
  s_trough_1:
    number: 20
    tags: trough, trough1
  s_trough_2:
    number: 21
    tags: trough, trough2
  s_trough_3:
    number: 22
    tags: trough, trough3
  s_trough_4:
    number: 23
    tags: trough, trough4
  s_trough_5:
    number: 24
    tags: trough, trough5
  s_trough_6:
    number: 25
    tags: trough, trough6
  s_trough_7:
    number: 26
    tags: trough, trough7
  s_trough_ball:
    number: 34
    tags: trough_ball
  s_trough_ball_jam:
    number: 33
    tags: trough_ball_jam
  
  # Shooter Lane
  s_shooter_lane:
    number: 0
    tags: shooter_lane
  
  # Outlanes and Inlanes
  s_outlane_right:
    number: 3C
    tags: playfield_active
  s_inlane_right:
    number: 3F
    tags: playfield_active
  s_inlane_left:
    number: 3E
    tags: playfield_active
  s_outlane_left:
    number: 38
    tags: playfield_active
  
  # Mode Opto
  s_mode_opto:
    number: 40
    tags: playfield_active
  
  # 3Bank Targets
  s_3bank_tgt_d:
    number: 32
    tags: playfield_active, dog_targets
  s_3bank_tgt_o:
    number: 31
    tags: playfield_active, dog_targets
  s_3bank_tgt_g:
    number: 35
    tags: playfield_active, dog_targets
  
  # Spinner
  s_spinner:
    number: 41
    tags: playfield_active
  
  # PopBumpers
  s_pop_bumper_1:
    number: 29
    tags: playfield_active, pop_bumpers
  s_pop_bumper_2:
    number: 2C
    tags: playfield_active, pop_bumpers
  s_pop_bumper_3:
    number: 2B
    tags: playfield_active, pop_bumpers
  
  # Ramps and Orbits
  s_ramp_up_1:
    number: 28
    tags: playfield_active
  s_right_orbit_1:
    number: 2A
    tags: playfield_active
  s_right_ramp_entry_1:
    number: 1B
    tags: playfield_active
  
  # Ball Lock Switches
  s_ball_lock_1:
    number: 18
    tags: playfield_active, ball_locks
  s_ball_lock_2:
    number: 19
    tags: playfield_active, ball_locks
  s_ball_lock_3:
    number: 1A
    tags: playfield_active, ball_locks
  
  # Slingshots
  s_left_slingshot:
    number: 3D
    tags: playfield_active
  s_right_slingshot:
    number: 3A
    tags: playfield_active
  
  # Newton
  s_newton_opto_made:
    number: 0  # Changed to 0 as no specific number was provided
    tags: playfield_active
  
  # Flipper EOS
  s_left_flipper_eos:
    number: 39
    tags: left_flipper_eos
  s_right_flipper_eos:
    number: 3B
    tags: right_flipper_eos
  
  # Button Controls
  s_start_button:
    number: 0A
    tags: start
  s_left_flipper_button:
    number: 08
    tags: left_flipper
  s_left_button_2:
    number: 09
  s_right_flipper_button:
    number: 10
    tags: right_flipper
  s_right_button_2:
    number: 11
  
  # Left Ramp Entry
  s_left_ramp_entry_1:
    number: 99
    tags: playfield_active

coils:
  c_trough:
    number: 34
    default_pulse_ms: 25
  c_left_flipper_main:
    number: 35
    default_pulse_ms: 30
  c_left_flipper_hold:
    number: 48
    allow_enable: true
  c_right_flipper_main:
    number: 36
    default_pulse_ms: 30
  c_right_flipper_hold:
    number: 49
    allow_enable: true
  c_left_slingshot:
    number: 37
    default_pulse_ms: 30
  c_right_slingshot:
    number: 38
    default_pulse_ms: 30
  c_mode_vuk:
    number: 39
    default_pulse_ms: 30
  c_upramp:
    number: 40
    default_pulse_ms: 30
  c_ramp_release:
    number: 41
    default_pulse_ms: 30
  c_diverter:
    number: 42
    default_pulse_ms: 30
  c_pop_bumper_1:
    number: 43
    default_pulse_ms: 25
  c_pop_bumper_2:
    number: 44
    default_pulse_ms: 25
  c_pop_bumper_3:
    number: 45
    default_pulse_ms: 25
  c_drop_target:
    number: 46
    default_pulse_ms: 30
  c_up_post:
    number: 47
    default_pulse_ms: 30

flippers:
  left_flipper:
    main_coil: c_left_flipper_main
    hold_coil: c_left_flipper_hold
    activation_switch: s_left_flipper_button
    eos_switch: s_left_flipper_eos
    enable_events: ball_started
    disable_events: ball_ending, service_mode_entered
  right_flipper:
    main_coil: c_right_flipper_main
    hold_coil: c_right_flipper_hold
    activation_switch: s_right_flipper_button
    eos_switch: s_right_flipper_eos
    enable_events: ball_started
    disable_events: ball_ending, service_mode_entered

autofire_coils:
  left_slingshot:
    coil: c_left_slingshot
    switch: s_left_slingshot
    enable_events: ball_started
    disable_events: ball_ending, service_mode_entered
  right_slingshot:
    coil: c_right_slingshot
    switch: s_right_slingshot
    enable_events: ball_started
    disable_events: ball_ending, service_mode_entered
  pop_bumper_1:
    coil: c_pop_bumper_1
    switch: s_pop_bumper_1
    enable_events: ball_started
    disable_events: ball_ending, service_mode_entered
  pop_bumper_2:
    coil: c_pop_bumper_2
    switch: s_pop_bumper_2
    enable_events: ball_started
    disable_events: ball_ending, service_mode_entered
  pop_bumper_3:
    coil: c_pop_bumper_3
    switch: s_pop_bumper_3
    enable_events: ball_started
    disable_events: ball_ending, service_mode_entered

ball_devices:
  bd_trough:
    ball_switches: s_trough_1, s_trough_2, s_trough_3, s_trough_4, s_trough_5, s_trough_6, s_trough_7
    eject_coil: c_trough
    tags: trough, home, drain
    jam_switch: s_trough_ball_jam
    eject_timeouts: 3s
    debug: true
  bd_shooter_lane:
    ball_switches: s_shooter_lane
    entrance_count_delay: 300ms
    eject_timeouts: 5s
    tags: launcher
  bd_ball_lock:
    ball_switches: s_ball_lock_1, s_ball_lock_2, s_ball_lock_3
    eject_coil: c_mode_vuk
    tags: ball_lock
    eject_timeouts: 2s

playfields:
  playfield:
    default_source_device: bd_shooter_lane
    tags: default

ball_saves:
  ball_save:
    active_time: 10s
    hurry_up_time: 3s
    grace_period: 2s
    enable_events: ball_started
    timer_start_events: balldevice_bd_shooter_lane_ball_eject_success
    auto_launch: true
    balls_to_save: 1

drop_targets:
  dt_dog_bank:
    switch: s_3bank_tgt_d, s_3bank_tgt_o, s_3bank_tgt_g
    reset_coil: c_drop_target
    reset_events:
      ball_starting: 1s

diverters:
  diverter:
    activation_coil: c_diverter
    type: hold
    debug: true
    activate_events: mode_ball_lock_started
    deactivate_events: mode_ball_lock_stopped
    
game:
  balls_per_game: 3
  max_players: 4

machine_vars:
  game_mode_dog_hunt_complete:
    initial_value: False
    persist: true
  game_mode_discovery_complete:
    initial_value: False
    persist: true
  game_mode_infected_complete:
    initial_value: False
    persist: true
  game_mode_blood_test_complete:
    initial_value: False
    persist: true
  game_mode_spider_head_complete:
    initial_value: False
    persist: true
  game_mode_wizard_complete:
    initial_value: False
    persist: true
  game_mode_ball_lock_complete:
    initial_value: False
    persist: true
  game_mode_multiball_complete:
    initial_value: False
    persist: true

counters:
  spinner_value:
    count_events: s_spinner_active
    starting_count: 0
    count_complete_value: 100
    events_when_complete: spinner_complete
    enable_events: ball_started
    disable_events: game_mode_active
    persist_state: false
    reset_on_complete: false
    restart_events: spinner_reset

  newton_hit_counter:
    count_events: s_newton_opto_made_active
    starting_count: 0
    count_complete_value: 3
    events_when_complete: newton_shots_complete
    enable_events: ball_started
    disable_events: game_mode_active
    persist_state: false
    reset_on_complete: false
    restart_events: newton_counter_reset

mode_settings:
  game_mode_active: false

event_player:
  # Dog Target Bank Completion
  s_3bank_tgt_d_active, s_3bank_tgt_o_active, s_3bank_tgt_g_active:
    - check_dog_bank_complete
  
  # Special Event to check if all 3 targets are active
  check_dog_bank_complete{device.switches.s_3bank_tgt_d.state and device.switches.s_3bank_tgt_o.state and device.switches.s_3bank_tgt_g.state}:
    - pulse_drop_target
    - dog_bank_targets_complete

  # Entry to VUK modes based on flow chart
  s_mode_opto_active{current_player.game_mode_active == false}:
    - check_available_modes

  # Spinner value reached
  spinner_complete{current_player.game_mode_active == false}:
    - enable_dog_hunt_mode
  
  # Left Ramp Events
  s_left_ramp_entry_1_active{current_player.game_mode_active == true}:
    - check_mode_progress

  # Right Ramp Events for Ball Lock
  s_right_ramp_entry_1_active{current_player.game_mode_active == true and current_player.game_mode == "ball_lock"}:
    - check_ball_lock_progress

  # Pulse the drop target when all DOG targets are hit
  pulse_drop_target:
    - coil_pulse: c_drop_target

timers:
  mode_timer:
    start_value: 60
    end_value: 0
    direction: down
    control_events:
      - event: mode_started
        action: start
      - event: mode_objective_complete
        action: stop
      - event: timer_mode_timer_complete
        action: restart
    events_when_complete: mode_timer_expired

scriptlets:
  service_mode:
    file: service_mode.py

modes:
  - base
  - attract
  - game
  - service
  - tilt
  - high_score
  - match
  - dog_hunt
  - discovery
  - infected
  - blood_test
  - spider_head
  - wizard
  - ball_lock
  - multiball
