#config_version=6


shots:

  dog_hunt_qualify:
    switch_sequence:
      - s_3bank_tgt_d_active
      - s_3bank_tgt_o_active
      - s_3bank_tgt_g_active
    sequence_type: in_order
    profile: default    
    show_tokens: {}
    events_when_complete: dog_hunt_qualified  
  
  spider_head_qualify:
    switch_sequence:
      - s_pop_bumper_1
      - s_pop_bumper_2
      - s_pop_bumper_3
    sequence_type: any
    profile: default
    repeat:
      count: 30
    show_tokens: {}
    events_when_complete: spider_head_qualified

  infected_qualify:
    switch_sequence:
      - s_left_ramp_enter
    sequence_type: any
    repeat:
      count: 3
    events_when_complete: infected_qualified

  blood_test_qualify:
    switch_sequence:
      - s_newton_opto_made
    sequence_type: any
    repeat:
      count: 3
    events_when_complete: blood_test_qualified

  discovery_qualify:
    switch_sequence:
      - s_spinner
    sequence_type: any
    repeat:
      count: 50
    events_when_complete: discovery_qualified

  wizard_qualify:
    switch_sequence:
      - s_right_orbit_1
    sequence_type: any
    repeat:
      count: 3
    events_when_complete: wizard_qualified


