#config_version=6

mode:
  start_events: mc_reset_phase_3, machine_reset_phase_3
  game_mode: False
  priority: 10
  code: attract.Attract
  stop_events: game_start

sound_player:
  mode_attract_started:
    main_song: 
      bus: music

#slide_player:
#  mode_attract_started:
#    attract:
#        target: main_screen

#  mode_attract_stopping:
#    attract:
#        action: remove

