#config_version=6

mode:
  start_events: mc_reset_phase_3, machine_reset_phase_3
  game_mode: False
  priority: 10
  code: attract.Attract
  stop_events: game_start

#No Longer used but kept as a code referance
#sound_player:
#  mode_attract_started:
#    main_song: 
#      bus: music

slide_player:
  mode_attract_started:
    attract:
