#config_version=6

mode:
  start_events: ball_starting
  priority: 100

# Handle events that happen when shots are completed or when modes should start
event_player:

# Enable the ball hold when any mode is started
  dog_hunt_qualify_lit_hit:
    - enable_bd_mode
    - balldevice_bd_mode_expected_ball
    - enable_ball_hold_mode_vuk_hold

  discovery_qualify_lit_hit:
    - enable_bd_mode
    - balldevice_bd_mode_expected_ball
    - enable_ball_hold_mode_vuk_hold

  infected_qualify_lit_hit:
    - enable_bd_mode
    - balldevice_bd_mode_expected_ball
    - enable_ball_hold_mode_vuk_hold

  blood_test_qualify_lit_hit:
    - enable_bd_mode
    - balldevice_bd_mode_expected_ball
    - enable_ball_hold_mode_vuk_hold

  spider_head_qualify_lit_hit:
    - enable_bd_mode
    - balldevice_bd_mode_expected_ball
    - enable_ball_hold_mode_vuk_hold

  # Only start modes that are qualified!
  "balldevice_bd_mode_ball_entered{player.dog_hunt_qualified > 0 and player.dog_hunt_complete == 0}":
    - log.info("Ball entered mode VUK with dog hunt qualified")
    - start_dog_hunt


  #"s_mode_opto_active{player.spider_head_qualified > 0 and player.spider_head_complete == 0}": start_spider_head
  #"s_mode_opto_active{player.infected_qualified > 0 and player.infected_complete == 0}": start_infected
  #"s_mode_opto_active{player.discovery_qualified > 0 and player.discovery_complete == 0}": start_discovery
  #"s_mode_opto_active{player.blood_test_qualified > 0 and player.blood_test_complete == 0}": start_blood_test

# Update player variables when shots are completed
variable_player:
  dog_hunt_qualify_lit_hit:
    dog_hunt_qualified:
      int: 1
      action: set  # Use 'set' instead of incrementing

  spider_head_qualify_lit_hit:
    spider_head_qualified:
      int: 1
      action: set

  discovery_qualify_lit_hit:
    discovery_qualified:
      int: 1
      action: set

  infected_qualify_lit_hit:
    infected_qualified:
      int: 1
      action: set

  blood_test_qualify_lit_hit:
    blood_test_qualified:
      int: 1
      action: set

  wizard_qualify_lit_hit:
    wizard_qualified:
      int: 1
      action: set

# Define the shots needed to qualify each mode
shots:
  dog_hunt_qualify:
    switches:
      - s_3bank_tgt_d
      - s_3bank_tgt_o
      - s_3bank_tgt_g
    sequence:
      in_order: true
    profile: default
    show_tokens: {}
    events_when_hit: dog_hunt_qualify_lit_hit

  spider_head_qualify:
    switches:
      - s_pop_bumper_1
      - s_pop_bumper_2
      - s_pop_bumper_3
    sequence:
      any_order: true
      hit_count: 30
    profile: default
    show_tokens: {}
    events_when_hit: spider_head_qualify_lit_hit

  infected_qualify:
    switches:
      - s_left_ramp_entry_1
    sequence:
      any_order: true
      hit_count: 3
    profile: default
    show_tokens: {}
    events_when_hit: infected_qualify_lit_hit

  blood_test_qualify:
    switches:
      - s_newton_opto_made
    sequence:
      any_order: true
      hit_count: 3
    profile: default
    show_tokens: {}
    events_when_hit: blood_test_qualify_lit_hit

  discovery_qualify:
    switches:
      - s_spinner
    sequence:
      any_order: true
      hit_count: 50
    profile: default
    show_tokens: {}
    events_when_hit: discovery_qualify_lit_hit

  wizard_qualify:
    switches:
      - s_right_orbit_1
    sequence:
      any_order: true
      hit_count: 3
    profile: default
    show_tokens: {}
    events_when_hit: wizard_qualify_lit_hit
