#config_version=6

mode:
  start_events: ball_started
  stop_events: ball_ending
  priority: 500  # High priority to handle mode qualification
  code: mode_qualifier.ModeQualifier

event_player:
  # Dog target bank completion qualifies dog hunt mode
  dog_bank_targets_complete{current_player.dog_hunt_complete == False}: qualify_dog_hunt_mode
  
  # When ball ends or mode completes, enable qualifications again
  ball_ending: enable_all_mode_qualifications
  mode_dog_hunt_complete: enable_all_mode_qualifications
  
  # Prevent multiple qualifications from stacking
  mode_qualification_achieved: disable_all_mode_qualifications

slide_player:
  # Slides for mode qualification
  qualify_dog_hunt_mode:
    mode_qualification:
      widgets:
        - type: text
          text: "DOG HUNT QUALIFIED! SHOOT THE VUK TO START!"
          font_size: 40
          y: center
          color: orange
          expire: 5s
  
  mode_qualification_achieved:
    qualification_instruction:
      widgets:
        - type: text
          text: "SHOOT THE CENTER VUK!"
          font_size: 45
          y: center-50
          color: red
          expire: 15s