#config_version=6

mode:
  start_events: ball_started
  stop_events: ball_ending
  priority: 500  # High priority to handle mode qualification
  code: mode_qualifier.ModeQualifier

event_player:
  # Dog target bank completion qualifies dog hunt mode
  dog_bank_targets_complete{current_player.dog_hunt_complete == False}: qualify_dog_hunt_mode
  
  # When ball ends or mode completes, enable qualifications again
  ball_ending: enable_all_mode_qualifications
  mode_dog_hunt_complete: enable_all_mode_qualifications
  
  # Prevent multiple qualifications from stacking
  mode_qualification_achieved: disable_all_mode_qualifications

#slide_player:
  # Slides for mode qualification
#  mode_dog_hunt_started:
#    mode_qualification:

