#config_version=6

mode:
  start_events: start_dog_hunt
  stop_events: dog_hunt_complete
  priority: 300
  code: dog_hunt.DogHunt
  
slide_player:
  mode_dog_hunt_started:
    base_slide:
      action: remove
    dog_hunt:

variable_player:
  spinner_hit:
    spinner_value: 1
  
  dog_hunt_complete:
    score: 50000

counters:
  spinner_counter:
    count_events: s_spinner_active
    events_when_hit: spinner_hit
    starting_count: 0
    count_complete_value: 100
    events_when_complete: spinner_value_complete
    persist_state: False

timers:
  dog_hunt_timer:
    start_value: 60
    end_value: 0
    direction: down
    control_events:
      - event: mode_dog_hunt_started
        action: start
      - event: dog_hunt_complete
        action: stop
    events_when_complete: dog_hunt_complete

event_player:
  spinner_value_complete: dog_hunt_complete
  timer_dog_hunt_timer_complete: dog_hunt_complete
