#config_version=6

mode:
  start_events: mode_wizard_start
  stop_events: mode_wizard_complete
  priority: 400  # Higher priority than regular modes
  code: wizard.Wizard
  
slide_player:
  mode_wizard_started:
    wizard_started:
      widgets:
        - type: text
          text: WIZARD MODE
          font_size: 70
          y: center-100
          color: yellow
          expire: 3s
          
  pop_bumper_hit_wizard:
    wizard_progress:
      widgets:
        - type: text
          text: "POP BUMPER VALUE: (player|pop_bumper_wizard) / 100"
          font_size: 30
          y: center
          color: white
          expire: 1s

variable_player:
  s_pop_bumper_1_active:
    pop_bumper_wizard: 1
    score: 5000
  s_pop_bumper_2_active:
    pop_bumper_wizard: 1
    score: 5000
  s_pop_bumper_3_active:
    pop_bumper_wizard: 1
    score: 5000
  
  wizard_complete:
    score: 500000
    
  # Add these to handle the player variables update
  set_wizard_complete:
    wizard_complete: 1
    
  set_game_mode_inactive:
    game_mode_active: 0
    
counters:
  pop_bumper_counter_wizard:
    count_events: s_pop_bumper_1_active, s_pop_bumper_2_active, s_pop_bumper_3_active
    events_when_hit: pop_bumper_hit_wizard
    starting_count: 0
    count_complete_value: 100
    events_when_complete: pop_bumper_complete_wizard
    persist_state: False
    
timers:
  wizard_timer:
    start_value: 60
    end_value: 0
    direction: down
    control_events:
      - event: mode_wizard_started
        action: start
      - event: wizard_complete
        action: stop
    events_when_complete: wizard_timer_expired
    
event_player:
  # Simple events
  pop_bumper_complete_wizard: wizard_objective_complete, phase1_wizard_complete
  wizard_timer_expired: wizard_failed
  wizard_objective_complete: mode_complete_light_wizard
  wizard_phase_2_complete: wizard_complete
  
  # Handle mode completion with proper event posting
  mode_wizard_complete: set_wizard_complete, set_game_mode_inactive, reset_all_modes
  
  # Conditional event
  "left_ramp_hit{current_player.current_game_mode=='wizard' and current_player.phase1_complete==true}": wizard_phase_2_advance