#config_version=6

mode:
  start_events: mode_blood_test_start
  stop_events: mode_blood_test_complete
  priority: 300
  code: blood_test.BloodTest
  
slide_player:
  mode_blood_test_started:
    blood_test_started:
      widgets:
        - type: text
          text: BLOOD TEST MODE
          font_size: 50
          y: center-100
          color: red
          expire: 2s
          
  newton_shot_made:
    blood_test_progress:
      widgets:
        - type: text
          text: "NEWTON SHOTS: (player|newton_shots) / 3"
          font_size: 30
          y: center
          color: white
          expire: 1s

variable_player:
  s_newton_opto_made_active:
    newton_shots: 1
    score: 15000
  
  blood_test_complete:
    score: 200000
    
counters:
  newton_shot_counter:
    count_events: s_newton_opto_made_active
    events_when_hit: newton_shot_made
    starting_count: 0
    count_complete_value: 3
    events_when_complete: newton_shots_complete
    persist_state: False
    
timers:
  blood_test_timer:
    start_value: 60
    end_value: 0
    direction: down
    control_events:
      - event: mode_blood_test_started
        action: start
      - event: blood_test_complete
        action: stop
    events_when_complete: blood_test_timer_expired
    
event_player:
  newton_shots_complete: blood_test_objective_complete
  blood_test_timer_expired: blood_test_failed
  blood_test_objective_complete: mode_complete_light_blood_test
  blood_test_phase_2_complete: blood_test_complete
  mode_blood_test_complete: update_player_var
  
  # Conditional event with quotes
  "left_ramp_hit{current_player.current_game_mode=='blood_test' and current_player.phase1_complete==true}": blood_test_phase_2_advance