#config_version=6

# Add machine-wide ball count
machine:
  balls_installed: 3  # Set this to match your actual ball count

hardware:
  platform: fast
  
fast:
  net:
    controller: neuron
    io_loop:
      cab:
        model: FP-I/O-0024
        order: 1
      3208:
        model: FP-I/O-3208
        order: 2
      "0804_1":  
        model: FP-I/O-0804
        order: 3
      "0804_2":
        model: FP-I/O-0804
        order: 4  
    port: com4
    baud: 921600
    debug: False
    watchdog: 1s

mpf:
  paths:
    modes: modes
  allow_invalid_config_sections: True
  save_machine_vars_to_disk: True

# Using an old-style config to include service mode yaml
config:
  - service_mode.yaml  # Include the service mode configuration
  - switches.yaml # All Switches
  - coils.yaml #All Coils
  - lights.yaml #All Lights
  - ball_devices.yaml #All Ball devices
  - autofire_coils.yaml #All Auto-Fire Coils
  - flippers.yaml #Flipper config
  - shots.yaml #Global shots for qualification here
  - events.yaml #Global events for qualifying modes here
  - variable_player.yaml #Mode logic here
  
# Add ball hold for the mode vuk
ball_holds:
  mode_vuk_hold:
    balls_to_hold: 1
    hold_devices: bd_mode
    release_one_events: release_mode_vuk_ball
    enable_events: mode_qualification_achieved
    disable_events: mode_started, ball_ending
    auto_release_after: 3s  # Changed from 20s to 3s for a better game flow

playfields:
  playfield:
    default_source_device: bd_shooter_lane
    tags: default

ball_saves:
  ball_save:
    active_time: 10s
    hurry_up_time: 3s
    grace_period: 2s
    enable_events: ball_started
    timer_start_events: balldevice_bd_shooter_lane_ball_eject_success
    auto_launch: False  # Disable auto-launch during ball lock mode
    balls_to_save: 1

drop_targets:
  front: 
    switch: s_3bank_tgt_d
  middle:
    switch: s_3bank_tgt_o
  back:
    switch: s_3bank_tgt_g

drop_target_banks:
    vuk_bank:
      drop_targets: front, middle, back
      reset_coil: c_drop_target
      reset_events: drop_target_bank_vuk_bank_down, game_started, ball_started
      reset_on_complete: 1s

diverters:
  diverter:
    activation_coil: c_diverter
    type: hold                 # Use hold type
    activation_time: 3s        # Hold for 3 seconds
    debug: True
    activate_events: activate_diverter, mode_ball_lock_started
    
game:
  balls_per_game: 3
  max_players: 4

# For virtual hardware testing, add virtual ball simulation
virtual_platform_start_active_switches:
  s_trough_6, s_trough_7, s_trough_ball

timed_switches:
  mode_vuk_delayed_eject:
    switch_tags: mode_opto
    time: 3s
    events_when_active: fire_mode_vuk_after_delay
    state_when_released: inactive

counters:
  spinner_value:
    count_events: s_spinner_active
    starting_count: 0
    count_complete_value: 100
    events_when_complete: spinner_complete
    enable_events: ball_started
    disable_events: game_mode_active
    persist_state: False
    reset_on_complete: False
    restart_events: spinner_reset

  newton_hit_counter:
    count_events: s_newton_opto_made_active
    starting_count: 0
    count_complete_value: 3
    events_when_complete: newton_shots_complete
    enable_events: ball_started
    disable_events: game_mode_active
    persist_state: False
    reset_on_complete: False
    restart_events: newton_counter_reset

  diverter_pattern:
    count_events: s_left_ramp_entry_1_active
    starting_count: 0
    count_complete_value: 5
    events_when_complete: diverter_pattern_complete
    reset_on_complete: True
    persist_state: False
    enable_events: ball_started
    restart_events: diverter_pattern_complete  # This resets and re-enables

  blood_target_counter:
    count_events: s_blood_target_active
    starting_count: 0
    count_complete_value: 4
    events_when_complete: mode_ball_lock_start
    events_when_hit: blood_target_qualify_hit
    reset_on_complete: True
    persist_state: False
    enable_events: ball_started
    disable_events: mode_ball_lock_started, game_mode_active  # Disable when ANY mode is active
    restart_events: mode_ball_lock_stopped, ball_started

event_player:
  # Basic switch events - changed pulse_drop_target event
  s_start_button_active: game_start
  s_3bank_tgt_d_active: check_dog_bank_complete
  s_3bank_tgt_o_active: check_dog_bank_complete
  s_3bank_tgt_g_active: check_dog_bank_complete
  s_mode_opto_active: check_mode_opto
  spinner_complete: check_spinner_complete
  ball_starting: bd_trough_eject
  diverter_pattern_complete: activate_diverter
  activate_diverter: 
    - release_diverter|3s
  
  # Ball Lock Events
  mode_ball_lock_started: enable_ball_lock_mechanism
  mode_ball_lock_stopped: disable_ball_lock_mechanism
  game_ending: multiball_lock_ball_lock_full
  
  # Ball lock handling
  "balldevice_bd_ball_lock_ball_count{value==3}":
    - multiball_lock_ball_lock_full
    - log_ball_lock_full
    - show_ball_lock_full_slide
  
  # Conditional events with quotes
  "s_mode_opto_active{current_player.game_mode_active == False}": check_available_modes
  "check_dog_bank_complete{device.switches.s_3bank_tgt_d.state and device.switches.s_3bank_tgt_o.state and device.switches.s_3bank_tgt_g.state}": dog_bank_targets_complete
  "spinner_complete{current_player.game_mode_active == False}": enable_dog_hunt_mode
  "s_right_ramp_entry_1_active{current_player.ball_lock_active == True}":
    - request_ball_lock
    
  # Game state events
  game_started: setup_game_variables
  ball_started: reset_player_shot_counters, pulse_upramp_on_start
  ball_ending: tally_player_score, enable_all_mode_qualifications
  
  # Mode-specific events
  dog_hunt_objective_complete: advance_game_state
  discovery_objective_complete: advance_game_state
  infected_objective_complete: advance_game_state
  blood_test_objective_complete: advance_game_state
  spider_head_objective_complete: advance_game_state
  wizard_objective_complete: advance_game_state
  multiball_lock_ball_lock_full: 
    - enable_multiball
    - release_locked_balls
  
  # Jackpot and scoring events
  jackpot_hit: award_jackpot_score
  super_jackpot_hit: award_super_jackpot
  
  # Timer events
  timer_dog_hunt_expired: end_dog_hunt_mode
  timer_discovery_expired: end_discovery_mode
  timer_infected_expired: end_infected_mode
  timer_blood_test_expired: end_blood_test_mode
  timer_spider_head_expired: end_spider_head_mode
  timer_wizard_expired: end_wizard_mode
  
  # Special shot events
  "newton_shots_complete{current_player.newton_shots >= 3}": enable_next_mode
  "pop_bumper_hit{current_player.pop_bumper_value >= 100}": award_pop_bumper_bonus
  
  # Prevent multiple qualifications from stacking - kept for compatibility with Python mode
  mode_qualification_achieved:
    - disable_all_mode_qualifications
    
  # Reset qualifications when mode completes
  mode_dog_hunt_complete: enable_all_mode_qualifications

  # Ball lock events
  ball_lock_hit:
    - increment_locked_balls
    - play_ball_lock_sound
    - update_ball_lock_lights

  #Blood Ball Lock events
  s_blood_target_active: check_blood_target  # New event
  blood_target_qualify_hit: show_blood_lock_progress

  # New ball lock related events
  ball_lock_eject_blocked:
    - log_ball_lock_eject_blocked

  ball_lock_requested:
    - log_ball_lock_request
    - update_ball_lock_request_lights

  ball_lock_request_error:
    - log_ball_lock_request_error
    - show_ball_lock_error_slide

  ball_lock_full:
    - log_ball_lock_full
    - show_ball_lock_full_slide

#slide_player:
#  show_blood_lock_progress:
#    blood_lock_qualify:
#      widgets:
#        - type: text
#          text: "BLOOD TARGET: (device.counters.blood_target_counter.value) / 4"
#          font_size: 30
#          y: center
#          color: red
#          expire: 2s

#  mode_ball_lock_start:
#    ball_lock_ready:
#      widgets:
#        - type: text
#          text: "BLOOD LOCK READY!"
#          font_size: 50
#          y: center
#          color: green
#          expire: 3s

#  ball_lock_request_error:
#    ball_lock_error:
#      widgets:
#        - type: text
#          text: "BALL LOCK ERROR!"
#          font_size: 40
#          y: center
#          color: red
#          expire: 2s

#  ball_lock_full:
#    ball_lock_full_warning:
#      widgets:
#        - type: text
#          text: "BALL LOCK IS FULL!"
#          font_size: 40
#          y: center
#          color: yellow
#          expire: 2s
          
  # New slides for mode qualification
#  qualify_dog_hunt_mode:
#    mode_qualification:
#      widgets:
#        - type: text
#          text: "DOG HUNT QUALIFIED! SHOOT THE VUK TO START!"
#          font_size: 40
#          y: center
#          color: orange
#          expire: 5s
  
#  mode_qualification_achieved:
#    qualification_instruction:
#      widgets:
#        - type: text
#          text: "SHOOT THE CENTER VUK!"
#          font_size: 45
#          y: center-50
#          color: red
#          expire: 15s

coil_player:
  dog_bank_targets_complete:
    c_drop_target:
      action: pulse
  
  pulse_drop_target:
    c_drop_target:
      action: pulse

  fire_mode_vuk_after_delay:
    c_mode_vuk:
      action: pulse

  activate_diverter:
    c_diverter:
      action: enable
      enable_ms: 3000
  
  release_diverter:
    c_diverter:
      action: disable
   
  enable_ball_lock_mechanism:
    c_ramp_release:
      action: pulse
  
  disable_ball_lock_mechanism:
    c_ramp_release:
      action: pulse
  
  fire_ramp_release:
    c_ramp_release:
      action: pulse
      
  multiball_lock_ball_lock_full:
    c_up_post:
      action: enable
      enable_ms: 3000

  pulse_upramp_on_start:
    c_upramp:
      action: pulse

modes:
  - base
  - attract
  - game
  - service
  - tilt
  - high_score
  - match
  - mode_switcher  # Add the new mode_switcher mode
  - dog_hunt
  - discovery
  - infected
  - blood_test
  - spider_head
  - wizard
  - multiball
  - ball_lock


# Logging configuration for ball lock events
logging:
  ball_lock_log:
    handlers:
      - console
      - file
    level: info
    file:
      filename: ball_lock_events.log
