#config_version=6

spider_head_qualified:
  spider_head_qualified: 1

dog_hunt_qualified:
  dog_hunt_qualified: 1

discovery_qualified:
  discovery_qualified: 1

infected_qualified:
  infected_qualified: 1

blood_test_qualified:
  blood_test_qualified: 1

wizard_qualified:
  wizard_qualified: 1
