#config_version=6

mode:
  start_events: start_infected
  stop_events: infected_complete
  priority: 300
  code: infected.Infected
  
slide_player:
  mode_infected_started:
    infected_started:
      widgets:
        - type: text
          text: INFECTED MODE
          font_size: 50
          y: center-100
          color: green
          expire: 2s
          
  left_ramp_hit:
    infected_progress:
      widgets:
        - type: text
          text: "LEFT RAMP HIT: (player|left_ramp_hits) / 3"
          font_size: 30
          y: center
          color: red
          expire: 1s

variable_player:
  left_ramp_hit:
    left_ramp_hits: 1
    score: 5000
  
  newton_hit:
    newton_hits: 1
    score: 5000      

  infected_complete:
    score: 150000
    
counters:
  left_ramp_counter:
    count_events: s_left_ramp_entry_1_active
    events_when_hit: left_ramp_hit
    starting_count: 0
    count_complete_value: 3
    events_when_complete: left_ramp_complete
    persist_state: False

  newton_counter:
    count_events: s_newton_opto_made
    events_when_hit: newton_hit
    starting_count: 0
    count_complete_value: 3
    events_when_complete: newton_complete
    persist_state: False

timers:
  infected_timer:
    start_value: 60
    end_value: 0
    direction: down
    control_events:
      - event: mode_infected_started
        action: start
      - event: infected_complete
        action: stop
    events_when_complete: infected_complete
    
event_player:
  left_ramp_complete: infected_objective1_complete
  newton_complete: infected_objective2_complete
  infected_objective_complete: infected_objective1_complete, infected_objective2_complete
  infected_timer_expired: infected_complete